### ISSUE TITLE
android@8.1 getting crashed while start the service

### ISSUE THREAD

**Issue by dassram17** [pmwisdom/cordova-background-geolocation-services#110]
android@8.1 getting crashed while start the service

**Comment by MaxKicw** [comment]
Hey @dassram17,

I had the same problem at Android 8 (API26+). I upgraded my working App from TargetApi 26 to TargetApi 28 (Android 8) and this Plugin didn't work anymore. It always caused a crash as the app started going into Background-Mode. 

**The Logs showed this error:**

`    --------- beginning of crash
2020-03-28 11:55:12.456 /? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: 
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**As it says in the new documentation from Android 8:**

> Before you can deliver the notification on Android 8.0 and higher, you must register your app's notification channel with the system by passing an instance of NotificationChannel to createNotificationChannel(). So the following code is blocked by a condition on the SDK_INT version

[https://developer.android.com/training/notify-user/build-notification](url)

**It works now with my adjustments**

So the crash is caused, because the notification of this plugin has no channel defined. After I found out about this problem, I created a copy of this plugin. I created a Notification Channel and added it to the notification of this plugin. Now it works find, without crashes!

[https://github.com/MaxKicw/background-activity-plugin](url)

Hope it helps! 

Not sure how we can merge my fix with this branch. Mabye need some help, If this ist possible :) @pmwisdom 

Cheers,
Max

**Comment by Smokolisz** [comment]
Hey @MaxKicw
I tried to install your plugin but i have hard time doing it. Can you provide which command i should use to install it?
I tried
`cordova plugin add https://github.com/MaxKicw/cordova-background-geolocation-services.git --save`
but it says:
`Failed to fetch plugin https://github.com/aklepaker/cordova-background-geolocation-services.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: Error: npm: Command failed with exit code 1 Error output:
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/aklepaker/cordova-background-geolocation-services.git
npm ERR!
npm ERR! Logon failed, use ctrl+c to cancel basic credential prompt.
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/aklepaker/cordova-background-geolocation-services.git/'
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Adam\AppData\Roaming\npm-cache\_logs\2020-12-24T11_42_04_811Z-debug.log`
