### ISSUE TITLE
Error on UWP

### ISSUE THREAD

**Issue by icedice** [pmwisdom/cordova-background-geolocation-services#19]
I know windows and UWP is not supported, but I'm having an issue. My app supports UWP and i use your plugin on Android and iOS platform. But the way Ionic/cordova works it tries to install plugins on all platforms (even the ones not supported) this works great for other (platform bound) plugins I use but your plugin thows this (which is a big pain in the a.. for me):

```
Installing "org.flybuy.cordova.background-location-services" for windows
Dependent plugin "cordova-plugin-geolocation" already installed on windows.
Failed to install 'org.flybuy.cordova.background-location-services':CordovaError: Uh oh!
"D:\projects\JobOnTheRun\app-new\plugins\org.flybuy.cordova.background-location-services\com.google.android.gms:play-services-location:+" not found!
    at copyFile (D:\projects\JobOnTheRun\app-new\platforms\windows\cordova\lib\PluginHandler.js:173:36)
    at handlers.framework.install (D:\projects\JobOnTheRun\app-new\platforms\windows\cordova\lib\PluginHandler.js:80:17)
    at Object.ActionStack.process (D:\projects\JobOnTheRun\app-new\platforms\windows\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at Api.addPlugin (D:\projects\JobOnTheRun\app-new\platforms\windows\cordova\Api.js:208:20)
    at handleInstall (C:\Users\tr\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:611:6)
    at C:\Users\tr\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:407:28
    at _fulfilled (C:\Users\tr\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\tr\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\tr\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\tr\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49Error: Uh oh!
"D:\projects\JobOnTheRun\app-new\plugins\org.flybuy.cordova.background-location-services\com.google.android.gms:play-services-location:+" not found!
```

Could you by any chance fix it so it just ignores (or install empty plugin or whatever other ppl do) this would be very appreciated.

**Comment by pmwisdom** [comment]
@icedice  Yep that will be an easy fix. Will try to get to today.

**Comment by pmwisdom** [comment]
Try commit 15b038b7005d673b6a559e97bfa0bce7f7b4d9c5 .

**Comment by icedice** [comment]
Awesome. Will try tomorrow when I'm back on work.

**Comment by icedice** [comment]
Works like a charm. Thanks a lot. Issue can be closed.
