### ISSUE TITLE
Failed to install 'org.flybuy.cordova.background-location-services': Error: ENOENT: no such file or directory, open '/Users/platforms/ios/moving/Plugins/Bridging-Header.h'

### ISSUE THREAD

**Issue by ghost** [pmwisdom/cordova-background-geolocation-services#33]
While i CLI install this plugin with ionic plugin add https://.......git i get below error on ionic cli 

Using this version of Cordova with older version of cordova-ios is being deprecated. Consider upgrading to cordova-ios@4.0.0 or newer.
The module "ConfigParser" has been factored into "cordova-common". Consider update your plugin hooks.
Creating new Bridging-Header.h at path:  /Users/platforms/ios/moving/Plugins/Bridging-Header.h
Failed to install 'org.flybuy.cordova.background-location-services':Error: ENOENT: no such file or directory, open '/Users/platforms/ios/moving/Plugins/Bridging-Header.h'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at createBridgingHeader (/Users/plugins/org.flybuy.cordova.background-location-services/hooks/add_swift_support.js:109:12)
    at run (/Users/plugins/org.flybuy.cordova.background-location-services/hooks/add_swift_support.js:45:34)
    at module.exports (/Users/plugins/org.flybuy.cordova.background-location-services/hooks/add_swift_support.js:11:5)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:187:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:165:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:133:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
Error: ENOENT: no such file or directory, open '/Users/platforms/ios/moving/Plugins/Bridging-Header.h'

**Comment by pmwisdom** [comment]
@appplumbr just tried this and could not reproduce with ionic CLI. Remove the iOS platform and add it back, that may solve your problems.
